# 3-3-2025 UTC+8 https://github.com/org/repo/new/mainbranch?repository_funding=1
# These are supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github:
  - xayanide
# Replace with a single Patreon username
patreon: xayanide
# Replace with a single Open Collective username
open_collective:
# Replace with a single Ko-fi username
ko_fi: xayanide
# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# tidelift:
# Replace with a single Community Bridge project-name e.g., cloud-foundry
# community_bridge:
# Replace with a single Liberapay username
# liberapay:
# Replace with a single IssueHunt username
# issuehunt:
# Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# lfx_crowdfunding:
# Replace with a single Polar username
# polar:
# Replace with a single Buy Me a Coffee username
buy_me_a_coffee: xayanide
# Replace with a single thanks.dev username
# thanks_dev:
# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom:
  - "https://www.paypal.com/paypalme/xayanide"
