name: Linters
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint-commit:
    permissions: write-all
    name: Lint commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commit
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: "./commitlint.config.mjs"
